name: 🚀 ROCKET LAUNCHING

on:
  workflow_dispatch:
#   workflow_call:
#     inputs:
#       app_name:
#         required: true
#         type: string
#       cluster_name:
#         required: true
#         type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"


#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
        
#       - name: print passthrough vars
#         run: |
#           echo "app_name: ${{ inputs.app_name }}"
#           echo "cluster: ${{ inputs.cluster_name }}"

#       - name: Login to Docker
#         run: |
#           docker login -u tiriyon -p ${{ secrets.DOCKER_PASS }}

#       - name: Build Docker image
#         run: docker build -t tiriyon/${{ inputs.app_name }}:${{ github.sha }} .

#       - name: Push Docker image
#         run: docker push tiriyon/${{ inputs.app_name }}:${{ github.sha }}
