name: Build Docker Image

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      cluster_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: print passthrough vars
        run: |
          echo "app_name: ${{ inputs.app_name }}"
          echo "cluster: ${{ inputs.cluster_name }}"

      - name: Login to Docker
        run: |
          docker login -u tiriyon -p ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t tiriyon/${{ inputs.app_name }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push tiriyon/${{ inputs.app_name }}:${{ github.sha }}
