name: Build Docker Image

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOEKN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN

      - name: Build Docker image
        run: docker build -t tiriyon/demo-workflow-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push tiriyon/demo-workflow-app:${{ github.sha }}
